[package]
name = "minimal_service_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncomm = { path = "../../", version = "0.1.0" }
ncomm_macro_derive = { path = "../../ncomm_macro_derive", version = "0.1.0" }